### ISSUE TITLE
writeRaw or any other way to add comments

### ISSUE THREAD

**Issue by xpahos** [FasterXML/jackson-dataformat-yaml#33]
I'm generating configs from database objects. Some fields should be added as comments. I found this method:

```java
    @Override
    public void writeRaw(String text) throws IOException, JsonGenerationException {
        _reportUnsupportedOperation();
    }
```
It's not implemented. Is there any reason to do not implement it? May be I can help with writeRaw* methods?

**Comment by cowtowncoder** [comment]
The reason this is unsupported is because low-level generation is using SnakeYAML, and I didn't notice method(s) that would allow injecting content. If a way is found, I'd be happy to merge a patch.

An easier alternative may be to add specific `writeComment()` method(s) in `YAMLGenerator` -- this does require direct calls (and possibly casts), but might be workable?

Yet another alternative would be to have a feature that makes all `writeRaw()` calls (or at least applicable ones; there are some exotic ones that require byte-write access) be written out as comments. That would allow databind "raw" writes through, even if only as comments.

**Comment by cowtowncoder** [comment]
Unfortunately it looks like SnakeYAML literally does not expose a way to write comments. That is rather... lame, for lack of better word. I might understand lack of readability due to difficulty. But lack of ability to write them? You got to be kidding me.

But it is what it is.

**Comment by cowtowncoder** [comment]
Also: attempts at implementing `writeRaw()` writing directly to underlying `Writer` lead nowhere.
Whether snakeyaml emitter flushes content eagerly or not seems arbitrary, and there are no levers to try to flush output.
