### ISSUE TITLE
Clarification on anchors in map collections

### ISSUE THREAD

**Issue by kevinteg** [FasterXML/jackson-dataformat-yaml#45]
I am trying to parse yaml generated by pyyaml and am running into problems parsing it in Jackson.  Sample:

    foo:
    - &id0001
      name: bar
      description: baz

There were two issues I encountered and I would really appreciate some input.

1) When I try to process this (after modification made in (2)), I get:

"Unresolved forward references for: Object id [1] (for class ...) at [Source: foo.yml; line: Y, column: X]."

If I modify the yaml to:

    foo:
    - &0001 name: bar
      description: baz

it processes fine.  The examples I have seen lead me to believe that the original format should work. http://yaml.org/YAML_for_ruby.html#aliases_and_anchors

I read the tests and found two examples, but didn't see one specifically for collection of maps.

[SimpleParseTest.java] (https://github.com/FasterXML/jackson-dataformat-yaml/blob/8a1961a203e69419ce90cbd68570f4400f352c81/src/test/java/com/fasterxml/jackson/dataformat/yaml/SimpleParseTest.java#L183)
[ObjectIdTest.java] (https://github.com/FasterXML/jackson-dataformat-yaml/blob/master/src/test/java/com/fasterxml/jackson/dataformat/yaml/ObjectIdTest.java#L32)

2)  pyyaml uses an anchor format of u'id%03d'.  From what I can tell, Jackson uses ints.  I modified anchor format in the pyyaml module, but I'm wondering if it is possible to use String anchors in Jackson.

Thanks in advance!

**Comment by cowtowncoder** [comment]
Ok, couple of notes here. First, yes, Jackson does support Object Ids, and yes, including Collection and Map values. Object Ids are treated as Strings, as well; even if underlying format used other scalars.

That said, one problem that might happen here is that conceptually Jackson would expect object id (anchor) to occur as part of value (String) token, and not before key value. Perhaps this can cause problem you observe.

I will try to reproduce your problem.

**Comment by cowtowncoder** [comment]
Oh. Should have read the full description here; I missed the part about id mismatch.

But I hope I can resolve that as well; in fact it may be a smaller problem altogether: maybe there is some handling that considers ids differently.

**Comment by cowtowncoder** [comment]
@kevinteg Ok, I can reproduce the problem you had, assuming you used examples from tests; as well as the way to get around the issues in question (or at least the one about numeric ids).

So: the challenge is that `ObjectIdGenerator` implementation has to understand ids well enough to both produce (generate) and read them, at least in general case. There are default ones that generate sequential `Integer` ids (one you probably used), as well as one that uses random `UUID`s.
However, no default implementation exists that would just take arbitrary `String` ids; mostly since there is no simple way to generate them. Although one could perhaps create one simply based on using `UUID`s to create them, but read any old ids. I may add an issue for `jackson-annotations` for this. There could be other ways too, using String prefixes, but one challenge with this is that there is no convenient way yet to configure generators via annotations.

Anyway: I added a new test method in `ObjectIdTest`, to show how one could implement alternate `ObjectIdGenerator`, and make usage work. I hope this helps in the meantime, if you still need a solution. Or maybe others find this useful as well.

**Comment by cowtowncoder** [comment]
For what it is worth 2.70 will now have `ObjectIdGenerators.StringIdGenerator` to use for this use case.
