### ISSUE TITLE
Lack of SnakeYAML Resolver leaves some missing features

### ISSUE THREAD

**Issue by benson-basis** [FasterXML/jackson-dataformat-yaml#50]
In SnakeYAML, several features of YAML are implemented above the parser in the 'Resolver' class. Jackson needs to use it to, amongst other things, support "~" as a syntax for null.

**Comment by benson-basis** [comment]
The question here is whether the dataformat should just use the Composer and the Node API, instead of the low-level parser. I'm going to try to avoid that for now.

**Comment by cowtowncoder** [comment]
Ok, thanks, I trust this makes sense. Some of low-level pieces seem kludgy, but since it's existing usage, and SnakeYAML is the de facto java decoder (there are no alternatives that would be faster; and the only other one barely has same functionality) I guess it's fine to rely on functionality it already has.

So I'll merge this in `master`, nicely in time for 2.7.0 release.

Thanks again!

**Comment by cowtowncoder** [comment]
For what it is worth, maven install works fine for me, so OSGi integration test seems to pass for me locally.

**Comment by cowtowncoder** [comment]
Will close for now; may re-file specific feature adds.
