### ISSUE TITLE
Support for deserializing YML file with no token ?

### ISSUE THREAD

**Issue by jvelo** [FasterXML/jackson-dataformat-yaml#81]
Use case is this : deserializing a default YML configuration file where everything is commented out, thus producing no token.

Mapper currently throws `JsonMappingException` with `No content to map due to end-of-input` message, since, as I understand, the parser expect at least one token.

Would that be a valid use case ? Is there a way to silence that exception and return a new instance of the value type instead I haven't seen ?

For reference, sample kotlin code I used for testing :

```
package configuration

import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory
import com.fasterxml.jackson.module.kotlin.KotlinModule
import org.junit.Test
import java.io.StringReader

data class FooBean(val foo: String = "bar")

class ConfigurationTests {

    @Test
    fun testDeserializeYmlWithNoTokenInFile() {
        val mapper = ObjectMapper(YAMLFactory())
        mapper.registerModule(KotlinModule())
        mapper.readValue(StringReader("""
# Un-comment the following to change "foo" configuration:
# foo: "bar"
"""), FooBean::class.java)
    }

}
```

**Comment by cowtowncoder** [comment]
@jvelo I think there is/was a similar issue filed against `jackson-databind`, and I think this is a general question. At this point I think answer is that filing an exception for simple `readValue()` is warranted because for many data formats returning `null` signifies explicit "null value" (like literal `null` token in JSON).

It is still possible to handle this case, with one of 2 work-arounds:

1. Construct parser instance directly, call `nextToken()`, and if it returns `null` (no content), handle it separately; otherwise call `readValue()` on `ObjectMapper` or `ObjectReader`
2. Construct `MappingIterator` via `ObjectReader.readValues()`: this is used for sequences of root-level values, and will allow sequences of 0 to N values. Then you can see if any values exist.

I hope this helps: if there are additional ideas for improvements, it may make most sense to discuss them on `jackson-dev` google group.

**Comment by jvelo** [comment]
Thanks for the detailed answer ; it makes sense.
