### ISSUE TITLE
YAMLFactory not parsing integers at all

### ISSUE THREAD

**Issue by mykobob** [FasterXML/jackson-dataformat-yaml#87]
I'm trying to use the YAMLFactory ObjectMapper to read in a .yaml file. However, there are issues with parsing the property in. 
```
public class YamlStuff {
  public static void main(String[] args) throws Exception {
    ObjectMapper mapper = new ObjectMapper(new YAMLFactory());
    mapper.configure(JsonParser.Feature.ALLOW_UNQUOTED_FIELD_NAMES, true);

    System.out.println(new YamlStuff().readValues(mapper));
  }

  public Integer readValues(ObjectMapper objectMapper) throws Exception {
    return objectMapper.readValue(
        new File("list.yaml"),
        new TypeReference<Integer>() {}
    );
  }
}
```
Jackson-dataformat-xml: 2.8.9, jackson-dataformat-yaml: 2.4.1

I can't parse Integers successfully, but parsing Longs instead of Integers works perfectly. I have an idea why, but no idea how to fix it.

**Comment by mykobob** [comment]
Related StackOverflow question that didn't help me: https://stackoverflow.com/questions/36895956/yaml-jackson-nullpointerexception-when-mapping-an-integer-property

**Comment by cowtowncoder** [comment]
@mykobob First of all: you should not (and typically, can not) use incompatible versions of modules -- so use version `2.8.9` of YAML module too: there is no reason to ever use something much older like `2.4.1`.
Upgrade could help.

Second: how does it fail? Is there an exception? Or value not working?
What does `list.yaml` contain -- a single number? Would it be possible to just include content to read in `String` instead of file?

**Comment by mykobob** [comment]
The contents in `list.yaml` is just an integer. This is just a test to be able to read integers. 

The error is a JsonMappingException 
```
Exception in thread "main" java.lang.NullPointerException
	at com.fasterxml.jackson.core.io.NumberInput.parseInt(NumberInput.java:30)
	at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:855)
	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:694)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:306)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:286)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2750)
	at YamlStuff.readValues(YamlStuff.java:31)
	at YamlStuff.main(YamlStuff.java:19)
```

**Comment by cowtowncoder** [comment]
@mykobob Sounds like I shoulld be able to -- I'll try to find time to work on this. Thank you for confirming the details.

**Comment by cowtowncoder** [comment]
Actually, no, I can not reproduce the issue.

So let me ask this again: Why are you trying to use ancient YAML module version? (as per my earlier comment)
2.4.1 may well have had issues, and it is possible this use of old (released 4 years ago) is the root cause.

**Comment by mykobob** [comment]
Yeah, upgrading the yaml library fixed it. So, should it just be that in the future, the version in jackson-databind:[version] and jackson-dataformat-yaml:[version] should be the same? Thanks for responding so quickly :)

**Comment by cowtowncoder** [comment]
@mykobob Yes, safest and least hassle is to use same version: minor part most important to match.

Requirements are such that usually "lowest level" components can be newer versions: so using, say, `jackson-core` of `2.8.8` for `jackson-dataformat-yaml` `2.4.1` would work in that no classloader errors should be found. But reverse would most likely fail, since newer yaml module would use some of methods added in later `jackson-core`. Similarly between `jackson-databind` that depends on `jackson-core`: databind may be lower version.

However there's no real benefit from mixing versions this way so it's just easiest to match them and avoid problems.
